### ISSUE TITLE
Update crates.io API token

### ISSUE THREAD

**Issue by Xcodo** [kraigher/rust_hdl#103]
v0.16.0 crates.io release action failed due to API key revocation.

> error: api errors (status 401 Unauthorized): The given API token does not match the format used by crates.io. Tokens generated before 2020-07-14 were generated with an insecure random number generator, and have been revoked. You can generate a new token at https://crates.io/me. For more information please see https://blog.rust-lang.org/2020/07/14/crates-io-security-advisory.html. We apologize for any inconvenience.

**Comment by kraigher** [comment]
I have updated the crates io token.
