### ISSUE TITLE
user-defined attributes for some entity classes are not supported

### ISSUE THREAD

**Issue by rroohhh** [kraigher/rust_hdl#34]
Similar to #31 `label`, `subtype`, `literal`, `units`,`group`,`file`,`property` and `sequence` is also not supported for user-defined attributes.

See IEEE Std 1076-2008 7.2 (p. 95):
```
attribute_specification ::=
    attribute attribute_designator of entity_specification is expression ;

entity_specification ::=
    entity_name_list : entity_class

entity_class ::=
    entity
    | architecture
    | configuration
    | procedure
    | function
    | package
    | type
    | subtype
    | constant
    | signal
    | variable
    | component
    | label
    | literal
    | units
    | group
    | file
    | property
    | sequence
```

**Comment by kraigher** [comment]
Which ones are you missing?

**Comment by rroohhh** [comment]
`label` is the one I am hitting right now

**Comment by kraigher** [comment]
I added the label entity class.

**Comment by rroohhh** [comment]
Awesome, together with #35 fixed it runs through my codebase without errors.

Should I leave the issue open, to track the other missing entity classes?

**Comment by kraigher** [comment]
yes leave it open
