### ISSUE TITLE
Replace from_utf8_unchecked with from_utf8

### ISSUE THREAD

**Issue by m-kru** [kraigher/rust_hdl#81]
Conversion from slice of bytes to utf-8 in latin_1.rs is done with  `from_utf8_unchecked`. 
From documentation:
```
Converts a slice of bytes to a string slice without checking that the string contains valid UTF-8.
```

I think it has been chosen  to achieve better performance, however in case of invalid UTF-8, the later execution may result with undefined behavior.

**Comment by kraigher** [comment]
If you are talking about the Latin-1 to utf-8 conversion the byte array is known to be utf-8 already since it was converted. A unit test exhaustively checks conversion of all 256 latin1 codes.
