### ISSUE TITLE
Rationale for Message and MessagePrinter structs.

### ISSUE THREAD

**Issue by m-kru** [kraigher/rust_hdl#87]
@kraigher would you be so kind to explain what is the rationale for `Message` and `MessagePrinter` structs? Do I understand correctly, that Message has been introduced to abstract the message exchanged with LSP client, but later you wanted to also print some of the messages in the `vhdl_lang` binary, so you have introduced `MessagePrinter`?

**Comment by kraigher** [comment]
Yes the point of the trait is to abstract the message consumer which could be either LSP pr stdout.

**Comment by m-kru** [comment]
Why no to use MessageType directly from lsp-types
```Rust
pub enum MessageType {
    /// An error message.
    Error = 1,
    /// A warning message.
    Warning = 2,
    /// An information message.
    Info = 3,
    /// A log message.
    Log = 4,
}
```
But introduce custom one
```Rust
pub enum MessageType {
    Error,
    Warning,
    Info,
    Log,
}
```
and then you do the conversion with
```Rust
fn to_lsp_message_type(message_type: &vhdl_lang::MessageType) -> MessageType {
    match message_type {
        vhdl_lang::MessageType::Error => MessageType::Error,
        vhdl_lang::MessageType::Warning => MessageType::Warning,
        vhdl_lang::MessageType::Info => MessageType::Info,
        vhdl_lang::MessageType::Log => MessageType::Log,
    }
}
```

You also decided to do the same with SrcPos. What am I missing?

**Comment by kraigher** [comment]
To avoid the non language server part from depending on the language server types.

**Comment by m-kru** [comment]
I have reopened to ask one more question. Why not to use only Diagnostic and convert diagnostic to LSP Message? Why Diagnostic and Message are separate entities, they look very similar?

**Comment by kraigher** [comment]
One is associated with a source code position and the other one is not. For example a syntax error is a diagnostic and a failure to open a file is a mesage.
