### ISSUE TITLE
Getting root of syntax tree for particular file.

### ISSUE THREAD

**Issue by m-kru** [kraigher/rust_hdl#88]
I would like to add functionality for generating .dot files with syntax tree graphs. It requires the root of the syntax tree for particular file.

Now, correct my if I am wrong anywhere.

It is impossible right now, because `design_unit` is a root for single syntax tree, not `design_file`. However, it looks like it is possible to get design units from particular file. First I need to get `DesignRoot` from `Project`. Then single `Library` from `DesignRoot`.  Next, from `units_by_source` hash map I can get `UnitId` for units coming from the file I am interested in. From `UnitId` I can fetch `UnitKey`. Then I have to come back to the `Library` and from `units` I can fetch `LockedUnit`.  `LockedUnit` contains `unit`, which contains `AnyDesignUnit`, which is the root of syntax tree for particular design unit.

I have mixed attribute names with type names, but I hope you understand.

If you had any implementation guidelines I'd really appreciate.

**Comment by kraigher** [comment]
You can just iterate over all design units and check the file name of the source position of the name of the design unit. Have a look at how ItemAtCursor is implemented.
